// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:powerocr/core/constants/enum.dart';
import 'package:powerocr/database/hive_entities/scan_history_entity/scan_history_entity.dart';
import 'package:powerocr/database/hive_entities/scan_text_block_history_entity/scan_text_block_history_entity.dart';
import 'package:powerocr/database/hive_entities/theme_setting_entity/theme_setting_entity.dart';
import 'package:powerocr/database/hive_entities/user_qr_entity/user_qr_entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ScanHistoryEntityAdapter());
    registerAdapter(ScanHistoryTypeAdapter());
    registerAdapter(ScanTextBlockHistoryEntityAdapter());
    registerAdapter(ThemeModeOptionAdapter());
    registerAdapter(ThemeSettingEntityAdapter());
    registerAdapter(UserQrEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ScanHistoryEntityAdapter());
    registerAdapter(ScanHistoryTypeAdapter());
    registerAdapter(ScanTextBlockHistoryEntityAdapter());
    registerAdapter(ThemeModeOptionAdapter());
    registerAdapter(ThemeSettingEntityAdapter());
    registerAdapter(UserQrEntityAdapter());
  }
}
