// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:powerocr/core/constants/enum.dart';
import 'package:powerocr/database/hive_entities/theme_setting_entity/theme_setting_entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ThemeModeOptionAdapter());
    registerAdapter(ThemeSettingEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ThemeModeOptionAdapter());
    registerAdapter(ThemeSettingEntityAdapter());
  }
}
