default_platform(:ios)

platform :ios do
  desc "Push a new release build to the TestFlight / App Store"
  lane :release do |options|
   
    # 1. Lấy API Key cho App Store Connect
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true,
      in_house: false
    )
    
    # 2. Tự động cập nhật Build Number từ GitHub Actions
    if options[:build_number]
      increment_build_number(
        build_number: options[:build_number],
        xcodeproj: "Runner.xcodeproj"
      )
    end
    
    # 3. Chạy các lệnh Flutter (Dùng Dir.chdir để quản lý path sạch sẽ)
    Dir.chdir("../..") do
      sh("flutter clean")
      sh("flutter pub get")
      sh("dart run build_runner build --delete-conflicting-outputs")
      
      # Build IPA dùng CLI Flutter - Tận dụng flag để không cần sửa file project.pbxproj bằng tay
      sh("flutter build ipa --release " \
         "--build-number=#{options[:build_number]} " \
         "--export-options-plist=ios/ExportOptions.plist " \
         "--obfuscate --split-debug-info=build/app/outputs/symbols")
    end
    
    # 4. Upload lên TestFlight
    upload_to_testflight(
      ipa: "../build/ios/ipa/*.ipa",
      skip_waiting_for_build_processing: true,
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false,
      un_precheck_before_submit: false
    )
  end
end
