default_platform(:ios)

platform :ios do
  desc "Push a new release build to the TestFlight / App Store"
  lane :release do |options|
    
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true,
      in_house: false
    )

    if options[:build_number]
      increment_build_number(
        build_number: options[:build_number],
        xcodeproj: "Runner.xcodeproj"
      )
    end

    # Biến để lưu đường dẫn tuyệt đối của IPA
    ipa_absolute_path = nil

    # Chạy lệnh Flutter ở thư mục gốc
    Dir.chdir("../..") do
      sh("flutter clean")
      sh("flutter pub get")
      sh("dart run build_runner build --delete-conflicting-outputs")
      
      sh("flutter build ipa --release " \
         "--build-number=#{options[:build_number]} " \
         "--export-options-plist=ios/ExportOptions.plist " \
         "--obfuscate --split-debug-info=build/app/outputs/symbols")

      # Tìm và lấy đường dẫn tuyệt đối chuẩn xác
      found_ipa = Dir["build/ios/ipa/*.ipa"].first
      ipa_absolute_path = File.expand_path(found_ipa) if found_ipa
    end

    # Kiểm tra an toàn
    unless ipa_absolute_path
      UI.user_error!("Không tìm thấy file IPA trong thư mục build của Flutter.")
    end

    # 4. Upload lên TestFlight với đường dẫn tuyệt đối
    upload_to_testflight(
      ipa: ipa_absolute_path,
      skip_waiting_for_build_processing: true
    )
  end
end