name: Deploy iOS to TestFlight / App Store

on:
  push:
    branches:
      - 'release/powerocr_v*' # Gắn hook: sẽ trigger khi push lên nhánh format là release/powerocr_vXYZ

jobs:
  deploy_ios:
    name: Build & Deploy iOS
    runs-on: macos-26
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.7'
          cache: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
          working-directory: ios

      - name: Generate .env File
        run: echo "API-KEY=${{ secrets.ENV_API_KEY }}" > .env

      - name: Inject GoogleService-Info.plist
        run: |
          echo -n "${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64 }}" | base64 --decode > ios/Runner/GoogleService-Info.plist

      # Tối ưu: Dùng Action chuyên dụng để cài Certificate
      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.IOS_BUILD_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.IOS_P12_PASSWORD }}

      # Tối ưu: Cài Provisioning Profile mà không cần tính UUID thủ công
      - name: Install Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n "${{ secrets.IOS_BUILD_PROVISION_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/temp.mobileprovision

      - name: Execute Fastlane Deployment
        working-directory: ios
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_CONTENT: ${{ secrets.ASC_KEY_CONTENT }}
        # Truyền github.run_number trực tiếp vào Fastlane
        run: bundle exec fastlane release build_number:${{ github.run_number }} --verbose
